#!/usr/bin/bash
container_name=${1:-cobot_vision}
docker container stop $container_name && docker container prune -f
DOCKER_BUILDKIT=1 docker build -f ./docker/mrcnn+pvnet.Dockerfile -t $container_name .
