# wait
cls_type: 'mainshell'
model: 'mainshell'
model_dir: 'data/model'
network: 'res'
heads: ''
task: 'pvnet'
gpus: (0, 1, 2, 3)
resume: true
skip_eval: false
save_ep : 5
eval_ep : 5

train:
    optim: 'adam'
    lr: 1e-3
    epoch: 250
    milestones: (20, 40, 60, 80, 100, 120, 160, 180, 200, 220)
    gamma: 0.5
    batch_size: 32
    dataset: 'FitTrain'
    cropresize_rate: 1.0
    rotate_rate: 1.0
    rotate_min: -30
    rotate_max: 30
    weight_decay: 0.
    batch_sampler: 'image_size'
test:
    dataset: 'FitTest'
    batch_size: 1
    batch_sampler: 'image_size'
    un_pnp: True